//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_comma.Views.User
{


    public partial class Orders
    {

        /// <summary>
        /// Contrôle lblOrderCount.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderCount;

        /// <summary>
        /// Contrôle lblStatus.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// Contrôle OrdersPanel.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel OrdersPanel;

        /// <summary>
        /// Contrôle OrdersRepeater.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater OrdersRepeater;

        /// <summary>
        /// Contrôle EmptyPanel.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel EmptyPanel;
    }
}
