//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_comma.Views.Admin
{


    public partial class Orders
    {

        /// <summary>
        /// Contrôle lblStatus.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// Contrôle OrdersRepeater.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater OrdersRepeater;
    }
}
